const express=require('express')
const bodyParser=require('body-parser')
const cors=require('cors')
const workshop=require('./ecrWorkshopFlow')
const authorize=require('./logging')
const seminar=require('./ecrSeminarFlow')
const ecrFilter=require('./ecrFilter')
const cfilter=require('./commonFilter')
const load=require('./loadAndApprove')
const iv=require('./iv_workflow')
const Nptel=require('./sesta_nptel')
const app=express()
const Vac=require('./sesta_vac')
const Intern=require('./sesta_internship')
const TechTalks1=require('./sesta_techtalks1')

app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use(cors())

app.use('/ecr',workshop)
app.use('',authorize)
app.use('/seminar',seminar)
app.use('/ecrFilter',ecrFilter)
app.use('/cfilter',cfilter)
app.use('/load',load)
app.use('/iv',iv)
app.use('/nptel',Nptel)
app.use('/vac',Vac)
app.use('/intern',Intern)
app.use('/techtalks1',TechTalks1)

app.listen(1234,()=>{
    console.log("App is running")
})